/**
 * ILMEK — the application catalog.
 *
 * The game's typed spine: one entry per real, public web application, giving it
 * a region, a stage, a puzzle system and a bilingual journal voice. Factual
 * metadata (name, description, sourceUrl) is mirrored verbatim from each
 * application's published page; shortConcept, mechanic, discovery and
 * completionCondition are the creative in-world adaptation written for play.
 * Ordered by region, then by the order applications appear in the regions.
 */

import type { ApplicationEntry } from '../types/catalog';

export const APPLICATIONS: readonly ApplicationEntry[] = [
  {
    code: 'AIA',
    slug: 'aia',
    name: { en: 'AI Ecosystem Atlas', tr: 'AI Ecosystem Atlas' },
    shortConcept: { tr: 'Terasda keşif makineleri aynı oyulmuş dünyada dolaşıp bulduklarını bildiriyor. Seninkinin sorusunu soranları tanıyıp aynı dili konuşanları tek bir haritada birbirine bağlıyorsun.', en: 'On the terrace, scout machines wander the same carved world and report what they found. You recognise the ones asking your question and wire those that speak alike into a single map.' },
    description: { en: 'An evidence-backed research console for comparing AI products and developer ecosystems.', tr: 'Yapay zekâ ürünlerini ve geliştirici ekosistemlerini kanıtlarıyla karşılaştıran araştırma konsolu.' },
    sourceUrl: 'https://aia.aserdargun.com/',
    region: 'cartographers-terrace',
    system: 'connection',
    stageId: 'r1-scout-match',
    mechanic: { tr: 'İki düğüm arasına kanal çekiyorsun. Kanal yalnızca aynı türden iki düğüm arasında kuruluyor ve her aktarma düğümü kendi kapasitesinden fazlasını iletmiyor: dar bir düğümün ardına geniş bir hat çekmek hiçbir şey kazandırmıyor. Adı verilen masaya belirli bir miktar ışık ulaştırıyorsun.', en: 'You draw a conduit between two nodes. A line only joins two nodes of the same kind, and every relay forwards no more than its own capacity, so a wide pipe past a narrow node buys nothing. You push a required amount of light to a named desk.' },
    discovery: { tr: 'Makineleri saymayı bıraktım, soruları saymaya başladım. Farklı yanıt veren iki keşifci hiç kayıp değilmiş; başka bir şeyi yanıtlıyormuşlar. Yine de bağladım onları — harita ayrılığı da tutmayı öğrendi.', en: 'I stopped counting machines and started counting questions. The two scouts that answered differently were never lost; they were answering something else. I wired them anyway, and the map learned to hold disagreement.' },
    questIds: ['r1-scout-match'],
    completionCondition: { tr: 'Tek bir kanal, hat boyunca yanlış türden bağlantı olmadan adı verilen masaya gereken ışığı taşır.', en: 'A single conduit carries the required light to the named desk with no mismatched junction anywhere in the line.' },
  },
  {
    code: 'POL',
    slug: 'pol',
    name: { en: 'POL — Programming Languages', tr: 'POL — Programlama Dilleri' },
    shortConcept: { tr: 'Terasın iki taş köprüsü aynı karşı kapıya varmak zorunda. İşaretleri farklı, geçiş aynı olmalı. Adımları geçişi ayakta tutan sırada diziyorsun.', en: 'Two stone bridges leave the terrace and must reach the same far gate. The symbols differ; the crossing must not. You lay the steps in the order that keeps the crossing standing.' },
    description: { en: 'English-only comparisons of the same tasks across programming languages: types, memory, paradigms and concurrency. Programming foundations that support GPU learning, but are not limited to GPU. Executed examples and hand-reviewed examples remain distinct.', tr: 'İngilizce arayüzle aynı görevleri programlama dilleri arasında karşılaştır: tipler, bellek, paradigmalar ve eşzamanlılık. GPU öğrenimini destekleyen programlama temelleri; kapsamı GPU ile sınırlı değil. Çalıştırılan örnekler ile elle incelenen örnekler ayrı tutulur.' },
    sourceUrl: 'https://pol.aserdargun.com/',
    region: 'cartographers-terrace',
    system: 'placement',
    stageId: 'r1-equivalent-bridges',
    mechanic: { tr: 'Adımları bir sıraya sürüklüyorsun, geçidi baştan sona o sırayla yürütüyor. Bir adım ancak gerektirdiği her şey hazır olduğunda çalışıyor; eksik, iki kez konmuş ya da engellenmiş bir adım yürüyüşü durduruyor ve yol diziyi ilk bozan adımı gösteriyor.', en: 'You drag steps into an order and the crossing runs them one by one. A step fires only when everything it requires is already true; a missing, duplicated or blocked step halts the run, and the trail names the first step that broke.' },
    discovery: { tr: 'İki yazım, tek geçiş. İki köprüyü de ayakta tuttuğumda birbirlerine dönüşmemişlerdi; yalnızca aynı iş sırasına karşı dürüst olmuşlardı.', en: 'Two spellings, one crossing. When both bridges finally held they had not become alike — they had only been honest about the same order of work.' },
    questIds: ['r1-equivalent-bridges'],
    completionCondition: { tr: 'Her adım tam bir kez yerleşmiş ve hiçbiri engellenmemiş olarak iki köprü de geçişi tamamlar.', en: 'Both bridges complete their crossing with every step placed exactly once and no step blocked.' },
  },
  {
    code: 'GPU',
    slug: 'gpu',
    name: { en: 'GPU Kernel Engineering — Kernel Atlas', tr: 'GPU Kernel Engineering — Kernel Atlas' },
    shortConcept: { tr: 'Tezgâhın kolları aynı anda tek iş dokuyor. İşi herkese bölünce her kolun hazırlığı yemeğe başlar; tek kola yığılırsa o kol hiç bitiremez. Sıra, hangi kola ne verileceğini bilmektir.', en: 'The loom arms each weave one job at a time. Spread the work thin and every arm pays a setup; pile it on one arm and that arm never finishes. The art is knowing which arm takes what.' },
    description: { en: 'A bilingual 12-week interactive atlas for CUDA, Triton, GPU memory, LLM operators, correctness, profiling, inference, and multi-GPU systems.', tr: 'CUDA, Triton, GPU belleği, LLM işleçleri, doğruluk, profil çıkarma, çıkarım ve çoklu GPU sistemleri için iki dilli, etkileşimli 12 haftalık atlas.' },
    sourceUrl: 'https://gpu.aserdargun.com/',
    region: 'flow-foundry',
    system: 'allocation',
    stageId: 'r2-loom-distribution',
    mechanic: { tr: 'İş birimlerini tezgâh kollarına yerleştiriyorsun. Kullanılan her kol bir kez hazırlık ödüyor, sonra işlerini sırayla taşıyor; bir kolda ancak yuvası kadar iş durabiliyor, yanlış türden iş de yer kaplıyor ve en uzun toplam yükü taşıyan kol tezgâhın ne zaman biteceğini belirliyor.', en: 'You place work units onto loom arms. Each used arm pays its setup once, then carries its jobs in sequence; an arm holds only as many jobs as it has slots, work of the wrong kind still takes room, and the arm with the heaviest total load sets when the loom is done.' },
    discovery: { tr: 'Kol ekleyerek tezgâhı hızlandırmadım. Kullanılmayan kolu bırakınca hızlandı: her boş yuva, kimsenin saymadığı ikinci bir hazırlıktı.', en: 'I never sped the loom up by adding arms. I sped it up by stopping to waste them — every empty slot had been a second setup nobody was counting.' },
    questIds: ['r2-loom-distribution'],
    completionCondition: { tr: 'Her iş yerleştirilir, hiçbir kol yuvasını ya da bir işin sabrını aşmaz ve en ağır kol belirlediği bitişi diğer kollar da yetiştirir.', en: 'Every job is placed, no arm passes its slot count or a job’s patience, and the heaviest arm sets a finish the other arms can meet.' },
  },
  {
    code: 'GEX',
    slug: 'gex',
    name: { en: 'GPU Execution Explorer', tr: 'GPU Yürütme Gezgini' },
    shortConcept: { tr: 'Bir iş parçası daha küçük mekiğlere bölünebilir. Soru bir mekiğin ne kadar hızlı gittiği değil, kaç mekiğin aynı yolda çarpışmadan birlikte yürüyebildiği.', en: 'One piece of work can be split into smaller shuttles. The question is not how fast a shuttle moves but how many travel the same road at once without colliding.' },
    description: { en: 'Trace GPU anatomy, kernel launches, warp masks, memory access, and matrix tiles through six interactive lessons. Results come from an educational execution model, not profiler measurements.', tr: 'Altı etkileşimli dersle GPU anatomisini, kernel başlatmayı, warp maskelerini, bellek erişimini ve matris bloklarını izle. Sonuçlar profil ölçümünden değil, eğitim amaçlı yürütme modelinden gelir.' },
    sourceUrl: 'https://gex.aserdargun.com/',
    region: 'flow-foundry',
    system: 'allocation',
    stageId: 'r2-loom-distribution',
    mechanic: { tr: 'Yükü birimlere bölüp şeritlere yerleştiriyorsun. Açılan her şerit sabit maliyetini ödüyor, şeritler birimlerini teker teker taşıyor, türü uymayan birim de yuvayı tüketiyor ve süreyi en ağır toplamı taşıyan şerit belirliyor.', en: 'You split the load into units and place them on lanes. Every lane opened pays its fixed cost, lanes carry their units one after another, a unit of the wrong kind still consumes a slot, and the lane with the heaviest total sets the time.' },
    discovery: { tr: 'Hızı tek bir mekiğin üzerinden okuyup buna sistem diyormuşum. Birlikte izlendiğinde hızlı ya da yavaş olan şey bütün yol.', en: 'I had been reading speed off a single shuttle and calling it the system. Watched together, the thing that is fast or slow is the whole road.' },
    questIds: ['r2-loom-distribution'],
    completionCondition: { tr: 'Birimlerin hepsi uygun türde, kapasite ve sabırları içinde birer şeride oturur ve hiçbir şerit diğerlerinden fazla yük taşımaz.', en: 'Every unit sits on a matching lane within its capacity and tolerance, and no lane carries more than any other.' },
  },
  {
    code: 'LLM',
    slug: 'llm',
    name: { en: 'LLM Runtime & Serving Atlas', tr: 'LLM Runtime & Serving Atlas' },
    shortConcept: { tr: 'Dökümhanede yedi kapı, her biri başka türden bir oda. Yanlış türden odaya giden iş odayı yine meşgul eder; yalnızca işe yarar bir şey getirmez.', en: 'Seven doors in the foundry, each a different kind of room. Work sent to the wrong kind of room still occupies it; it simply returns nothing useful.' },
    description: { en: 'A source-backed field guide to LLM runtimes and serving engines across seven architectural layers, with an interactive learning layer.', tr: 'LLM çalıştırma ortamlarını ve sunma motorlarını yedi mimari katmanda sınıflandıran, etkileşimli öğrenme katmanına sahip kaynaklı alan rehberi.' },
    sourceUrl: 'https://llm.aserdargun.com/',
    region: 'flow-foundry',
    system: 'allocation',
    stageId: 'r2-chamber-routing',
    mechanic: { tr: 'Her işi bir oda şeridine atıyorsun. Şeritler yalnızca kendi türünü kabul ediyor, kullanılan şerit sabit bir giriş ücreti ödüyor, yuvası aşan şerit kendini aşırı yüklü diye bildiriyor ve yanlış yere konan birim misrouted sayılıyor — yeri de yine kaplıyor.', en: 'You assign each work unit to a chamber lane. Lanes accept only their own kind, a used lane pays a fixed entry cost, a lane past its slot count reports itself as overloaded, and a unit placed where it does not belong is flagged as misrouted even though it still takes room.' },
    discovery: { tr: 'Yedinci oda hiçbir zaman yavaş olan değildi. Yanıtlayamayacağı işleri sessizce üstlenen odaları oydu.', en: 'The seventh room was never the slow one. It was the room quietly taking work it had no way to answer.' },
    questIds: ['r2-chamber-routing'],
    completionCondition: { tr: 'Her iş birimi kendi türündeki bir odaya ulaşır, hiçbir şerit yuvalarını aşmaz ve hiçbir iş atanmamış olarak kalmaz.', en: 'Every work unit reaches a chamber of its own kind, no lane exceeds its slots, and no work is left unassigned.' },
  },
  {
    code: 'TFL',
    slug: 'tfl',
    name: { en: 'TFL — Token Flow Laboratory', tr: 'TFL — Token Akışı Laboratuvarı' },
    shortConcept: { tr: 'Mekiğe öbek Dökümhaneden geçiyor. Bazı mekiğler önce hazırlanmalı; başkası ancak kendinden öncekiler için yer ayrıldıktan sonra çıkabiliyor.', en: 'A caravan of tokens crosses the foundry. Some tokens must be prepared before any may leave; others may only go once room has been reserved for everything ahead of them.' },
    description: { en: 'Explore nine deterministic serving experiments and ten guided checkpoints: queueing, prefill, KV reservations, decode and token delivery. Compare scheduling, latency and throughput; token text is scripted and timings are synthetic, with no model execution or hardware benchmark.', tr: 'Dokuz deterministik sunum deneyi ve on rehberli kontrol noktasıyla kuyruk, ön doldurma, KV rezervasyonları, çözümleme ve token iletimini keşfet. Zamanlama, gecikme ve verimi karşılaştır; token metni hazırlanmıştır, süreler sentetiktir. Gerçek model veya donanım kıyaslaması çalışmaz.' },
    sourceUrl: 'https://tfl.aserdargun.com/',
    region: 'flow-foundry',
    system: 'placement',
    stageId: 'r2-caravan-schedule',
    mechanic: { tr: 'Mekiğenin aşamalarını sıralıyorsun. Her aşama yalnızca gerektirdiği sinyaller hazır olduğunda koşuyor, her aşama tam bir kez yer almalı ve değerlendirici belirsiz bir başarısızlık yerine zinciri ilk kıran aşamayı adıyla bildiriyor.', en: 'You order the caravan’s stages. A stage runs only when the signals it requires are already true, every stage must appear exactly once, and the evaluator reports the first stage that broke the chain instead of failing vaguely.' },
    discovery: { tr: 'Mekiğe hiçbir zaman geç kalmadı. Erken gelmişti; kendisine ihtiyaç duyulan aşamayı kendinden sonraya planlayıp kapıda bekliyordu.', en: 'The caravan was never late. It was early, standing at the gate while I had scheduled the stage it needed after the stage it needed.' },
    questIds: ['r2-caravan-schedule', 'cross-x3'],
    completionCondition: { tr: 'Mekiğenin bütün aşamaları tam bir kez ve hiçbir aşamanın kendinden önceki bir aşamanın sağlaması gerekenini eksik bulmayacağı bir sırada yer alır.', en: 'All caravan stages appear exactly once in an order where no stage is ever missing something an earlier stage should have supplied.' },
  },
  {
    code: 'HNS',
    slug: 'hns',
    name: { en: 'Harness Engineering Observatory', tr: 'Harness Engineering Observatory' },
    shortConcept: { tr: 'Gözlemevi tek bir makine değil, üst üste binmiş yedi odadan oluşur. Sırasız koşan bir iş gürültüyle çökmüyor; yalnızca yanlış oda önceden ısınmış olarak karşınıza çıkıyor.', en: 'The observatory is not one machine but seven rooms stacked on each other. A task that runs out of order does not fail loudly; it simply arrives with the wrong room already warm.' },
    description: { en: 'A bilingual, source-backed observatory comparing seven agent-system layers: execution, tools, context, lifecycle, observability, verification, and governance. Evidence and editorial interpretation remain separate; no universal ranking.', tr: 'Çalıştırma, araçlar, bağlam, yaşam döngüsü, gözlemlenebilirlik, doğrulama ve yönetişimden oluşan yedi ajan sistemi katmanını karşılaştıran iki dilli, kaynaklı gözlemevi. Kanıt ve editoryal yorum ayrıdır; evrensel sıralama üretmez.' },
    sourceUrl: 'https://hns.aserdargun.com/',
    region: 'memory-council-city',
    system: 'placement',
    stageId: 'r3-task-sequence',
    mechanic: { tr: 'Yedi katmanı bir çalışma sırasına diziyorsun. Her katman altındaki sinyali bekliyor; iki kez konan ya da atlanan katman kendi başına bildiriliyor ve ön koşulu olmadan koşan ilk katman hatayı gösteriyor.', en: 'You arrange the seven layers into an execution order. Each layer waits for the signal below it, a layer used twice or left out is reported on its own, and the first layer that ran without its precondition names the failure.' },
    discovery: { tr: 'Yıllarca yedinci odayı suçlamıştım. O, altıncı bitirmeden ona bir şey söylenen ilk odaydı; sadece ilk o.', en: 'I had blamed the seventh room for years. It was simply the first room to be told something the sixth one had not finished.' },
    questIds: ['r3-task-sequence'],
    completionCondition: { tr: 'Yedi katmanın tamamı tam bir kez ve her biri yalnızca ihtiyaç duyduğu sinyal var olduğunda başlayan bir sırada yer alır.', en: 'All seven layers appear exactly once in an order where each one starts only after the signal it requires already exists.' },
  },
  {
    code: 'ARL',
    slug: 'arl',
    name: { en: 'ARL — Agent Runtime Laboratory', tr: 'ARL — Ajan Çalışma Zamanı Laboratuvarı' },
    shortConcept: { tr: 'Bir işçinin bütün bir çalışması tezgâha serilip adım adım yeniden oynatılabiliyor. Her adımı taşıyabilirsin; taşıyamadığın şey, dünyanın zaten dayandığı sıra.', en: 'A whole run of a worker can be laid out on a bench and replayed step by step. You may move any step; what you cannot move is the order the world already depends on.' },
    description: { en: 'Inspect a deterministic agent run through harness, context, security and evaluation lenses. Explore tool use, evidence and one-use approval; all actions remain inside the simulation.', tr: 'Deterministik bir ajan yürütmesini harness, bağlam, güvenlik ve değerlendirme açısından incele. Araç kullanımını, kanıtları ve tek kullanımlık onayı keşfet; tüm eylemler simülasyon içinde kalır.' },
    sourceUrl: 'https://arl.aserdargun.com/',
    region: 'memory-council-city',
    system: 'placement',
    stageId: 'r3-task-sequence',
    mechanic: { tr: 'Çalışmanın adımlarını yeni bir sıraya sürüklüyor, yolun aydınlanmasını izliyorsun. Gereksinimleri henüz karşılanmamış bir adım diziyi durduruyor; yol en erken böyle adımı bildirdiği için tahminle uğraşmak yerine zinciri onarıyorsun.', en: 'You drag the run’s steps into a new order and watch the trail light up. A step whose requirements are unmet stops the sequence, and the trail reports the earliest such step, so you repair the chain instead of guessing at it.' },
    discovery: { tr: 'Çalışmanın hiçbir şeyi yanlış değildi. Adımlar doğruydu; yanlış olan, günün hangi saatinde koştuklarıydı.', en: 'Nothing in the run was wrong. The steps were right; the hour they ran in was wrong.' },
    questIds: ['r3-task-sequence'],
    completionCondition: { tr: 'Çalışmanın her adımı tam bir kez yer alır ve hiçbir adım bağımlı olduğu koşul sağlanmadan başlamaz.', en: 'Every step of the run appears exactly once and no step starts before the condition it depends on has been met.' },
  },
  {
    code: 'DPL',
    slug: 'dpl',
    name: { en: 'DPL — Decision Plane Laboratory', tr: 'DPL — Karar Düzlemi Laboratuvarı' },
    shortConcept: { tr: 'Her kavşakta küçük bir oda bir kapı sunar. Biri kısadır, biri daha uzun bakmanı ister, biri imza bekler, biri de yalnızca reddeder. Oda senin seçimini sayar.', en: 'At every junction a small room offers a door. One is short, one asks you to look longer, one asks you to wait for a signature, one simply refuses. The room counts what you chose.' },
    description: { en: 'An independent deterministic simulation for the decision plane: take a short path, evaluate further, ask for evidence, wait for approval, abstain or block an action.', tr: 'Karar düzlemi için bağımsız, deterministik simülasyon: kısa yolu seç, ek değerlendirme yap, kanıt iste, onay bekle, çekimser kal veya eylemi engelle.' },
    sourceUrl: 'https://dpl.aserdargun.com/',
    region: 'memory-council-city',
    system: 'prediction',
    stageId: 'r3-junction-choice',
    mechanic: { tr: 'Kavşakta bir karar veriyorsun: ilerle, kanıt iste, bekle ya da çekimser kal. Kararın bir sonucu var ama kararın kendisi doğru demek yetmiyor; sonra gerçekten hangi mekanizmanın kıpırdadığına bakıyorsun.', en: 'You choose at a junction: proceed, ask for evidence, wait, or withhold judgement. Every choice has an outcome, but making one is not by itself being right; afterwards you check which mechanism actually responded.'},
    discovery: { tr: 'Kısa kapı hiçbir zaman bilgelikle seçilmedi. Onu, uzun olanın istediğini taşımak zorunda tutulmamış herkes seçti.', en: 'The short door was never chosen by wisdom. It was chosen by everyone who had not yet been made to carry what the long one asks for.' },
    questIds: ['r3-junction-choice', 'cross-x2'],
    completionCondition: { tr: 'Fener kavşağın gerektirdiği kanıtı alır, yer sıkıntısıyla hiçbir şeyi dışarıda bırakmaz ve bayat ya da yanlış kayıt taşımaz.', en: 'The lantern admits the evidence the junction requires, drops nothing for lack of room, and carries no record that is stale or false.' },
  },
  {
    code: 'CUL',
    slug: 'cul',
    name: { en: 'CUL — Computer Use Laboratory', tr: 'CUL — Bilgisayar Kullanımı Laboratuvarı' },
    shortConcept: { tr: 'Bir ele hangi düğmeyi çevireceğini söylersin; el çevirdiğini bildirir, atölye ise gerçekte neyin kıpırdadığına bakar. Bunlar iki ayrı iddia.', en: 'You tell a hand which knob to turn, the hand reports that it did so, and the workshop checks what actually moved. Those are two different claims.' },
    description: { en: 'Observe, act, verify: synthetic computer-use scenarios that keep targeting, approval and result checking inside one controlled browser environment.', tr: 'Gözlemle, eyleme geç, doğrula: hedefleme, onay ve sonuç denetimini tek bir kontrollü tarayıcı ortamında tutan sentetik bilgisayar kullanımı senaryoları.' },
    sourceUrl: 'https://cul.aserdargun.com/',
    region: 'memory-council-city',
    system: 'prediction',
    stageId: 'r3-junction-choice',
    mechanic: { tr: 'Eylemi seçiyor, koşumunu izliyor ve sonra doğruluyorsun. Rapor kıpırdırmayı amaçladığın mekanizmayı gerçekten kıpırdayanla karşılaştırıyor; ancak ikisi aynıysa ve eylemin kendisi de başarısız olmadıysa doğrulanmış sayıyor.', en: 'You choose the action, watch it run, then verify. The report compares the mechanism you intended to move against the one that actually moved, and counts it as verified only when they match and the action itself did not fail.' },
    discovery: { tr: 'El hiçbir zaman yalan söylememişti. Yalnızca açtığı kapıyı bildiriyordu; ben ise pencereyi sormuştum.', en: 'The hand had never lied. It simply reported the door it opened, while I had asked about the window.' },
    questIds: ['r3-junction-choice'],
    completionCondition: { tr: 'Yanıt veren mekanizma amaçlanan mekanizma olduğunda eylem onaylanır; yalnızca başarılı koşum kanıt sayılmaz.', en: 'An action is confirmed only when the mechanism that responded is the one that was intended; a successful run alone is not accepted as proof.' },
  },
  {
    code: 'AOS',
    slug: 'aos',
    name: { en: 'Agent Operating System', tr: 'Ajan İşletim Sistemi' },
    shortConcept: { tr: 'Atölyenin işçisi hiç uyumaz ama hareketinin ortasında durdurulabilir, başka bir iş verilebilir ve yeniden başlatılabilir; ama yalnızca bu sırayla.', en: 'The workshop’s worker never sleeps, but it can be stopped mid-motion, given a different job and started again — and only in that order.' },
    description: { en: 'A public guide to a target agent operating-system architecture: local models, an isolated computer, an open state and human control.', tr: 'Hedef ajan işletim sistemi mimarisini anlatan kamusal rehber: yerel modeller, izole bir bilgisayar, açık durum ve insan kontrolü.' },
    sourceUrl: 'https://aos.aserdargun.com/',
    region: 'memory-council-city',
    system: 'evidence',
    stageId: 'r3-worker-supervision',
    mechanic: { tr: 'İşçiyi yasal geçişlerinden geçiriyorsun: koşuyor, duraklatıldı, yeniden görevlendirildi, yeniden başladı, yeniden koşuyor. Her yeniden görevlendirmenin kendisine verilen kanıtı taşıdığını denetliyorsun; yasadışı bir sıçrama reddedilir ve kayıt tazelenene kadar şüpheli kalır.', en: 'You drive the worker through its legal transitions — running to paused, paused to retasked, retasked to resumed, resumed back to running — and check that each retask carries the evidence it was assigned with. An illegal jump is refused and the record stays suspect until refreshed.' },
    discovery: { tr: 'İşçi hiçbir zaman yanıtsız değildi. Onu dinlemek için duraklatıyor, sessizliği yanıt diye adlandırıyordum.', en: 'The worker was never unresponsive. I was pausing it to listen, and calling the silence an answer.' },
    questIds: ['r3-worker-supervision'],
    completionCondition: { tr: 'İşçi yalnızca yasal sırayla koşar duruma ulaşır ve en son görevinin arkasındaki kayıt taze, doğrulanmış olarak ona taşınır.', en: 'The worker reaches a running state through the legal sequence only, and the record behind its latest task is fresh, verified and carried into it.' },
  },
  {
    code: 'AGR',
    slug: 'agr',
    name: { en: 'Agora', tr: 'Agora' },
    shortConcept: { tr: 'Halkanın üzerinde yedi koltuk. Her biri önce tek başına yanıtlar, sonra diğerlerini isimle yanıtlar, sonra karşı çıkanlar bir kez daha çağrılır. Halka uzlaşıp uzlaşmadığını bildirir; doğru olup olmadıklarını değil.', en: 'Seven seats in a ring. Each answers alone first, then answers the others by name, then the dissenters are called back once. The ring reports whether they agreed — not whether they were right.' },
    description: { en: 'A deliberation panel of OpenRouter’s free models. Every seat answers the proposition alone, then answers the other seats by name, and the dissenters are invited back once more. Agora counts the discussion itself and reports whether the panel converged, measured against a bar it declares in advance. Agreement is reported as agreement, never as correctness.', tr: 'OpenRouter’ın ücretsiz modellerinden oluşan bir müzakere paneli. Her üye öneriyi önce tek başına yanıtlıyor, sonra diğer koltuklara isimleriyle cevap veriyor, karşı çıkanlar bir kez daha çağrılıyor. Agora sayımı kendisi yapıyor ve panelin uzlaşıp uzlaşmadığını önceden ilan ettiği bir eşikle bildiriyor. Uzlaşı, uzlaşı olarak raporlanır; asla doğruluk olarak değil.' },
    sourceUrl: 'https://agr.aserdargun.com/',
    region: 'memory-council-city',
    system: 'evidence',
    stageId: 'r3-council-chamber',
    mechanic: { tr: 'Her koltuğun tek başına verdiği ilk yanıtı, sonra diğerlerine verdiği yanıtları dinliyor ve halkanın hangi varsayımda uzlaştığını okuyorsun. Uzlaşı yalnızca uzlaşıdır: paylaşılan varsayım arşivce çürütüldüğünde salon kararı onaylamaz ve yanlış uzlaşıyı adıyla bildirir.', en: 'You listen to each seat’s separate first answer, then to its answers to the others, and read which assumption the ring converged on. Agreement is only agreement: when the shared assumption is contradicted by the archive, the chamber refuses to certify the decision and names the false consensus.' },
    discovery: { tr: 'Yedi ses, tek bir cümle; hiçbiri tarif ettiği pencereyi kontrol etmemişti.', en: 'Seven voices, one sentence, and not one of them had checked the window it described.' },
    questIds: ['r3-council-chamber'],
    completionCondition: { tr: 'Halka arşivin çürütmediği bir varsayımda uzlaşır ve salon bu uzlaşıyı kanıt saymadan onaylar.', en: 'The ring converges on an assumption the archive does not contradict, and the chamber certifies that agreement rather than treating it as proof.' },
  },
  {
    code: 'CTX',
    slug: 'ctx',
    name: { en: 'Context & Knowledge Engineering', tr: 'Bağlam ve Bilgi Mühendisliği' },
    shortConcept: { tr: 'Kimse yanıtlamadan önce bir şeyler taşımalıdır. Fenerin karnı sabittir ve ilgisiz sayfalar, bir şeyi değiştiren tek sayfayı dışarı iter.', en: 'Before anyone can answer, they must carry something. The lantern has a fixed belly, and irrelevant pages crowd out the one page that mattered.' },
    description: { en: 'A bilingual, source-backed field guide to the information system that runs before a model answers, from ingestion and retrieval through citation, caching, and memory.', tr: 'Model yanıtından önce çalışan bilgi sistemini alım ve erişimden alıntılama, önbellekleme ve belleğe kadar tasarlamaya yarayan iki dilli, kaynaklı alan rehberi.' },
    sourceUrl: 'https://ctx.aserdargun.com/',
    region: 'memory-council-city',
    system: 'evidence',
    stageId: 'r3-context-lantern',
    mechanic: { tr: 'Hangi kayıtların fenere gireceğine ve hangi sırayla karar veriyorsun. Kapasite sınırlı, her kayıt taşıdığı etiket sayısı kadar yer kaplıyor; sınırın ötesindeki her şey dışarı atılıyor, gerekli her etiket temsil ediliyor ve fenerde bayat ya da yanlış kayıt kalmıyor.', en: 'You choose which records enter the lantern and in what order. Capacity is finite, each record costs room in proportion to how many tags it carries, anything past the limit is crowded out, every required tag must be represented, and no admitted record may be stale or false.' },
    discovery: { tr: 'Yanıt hiçbir zaman kısa değildi. Yanımdaki üç ilgisiz sayfayı da paketleyene kadar kısalmıştı.', en: 'The answer was never short. It was short only until I packed it beside three pages that had nothing to do with it.' },
    questIds: ['r3-context-lantern'],
    completionCondition: { tr: 'Fener gerekli her etiketi, yer sıkıntısıyla dışarıda bırakılan hiçbir şey olmadan ve bayat ya da yanlış kayıt taşımadan taşır.', en: 'The lantern carries every required tag with nothing crowded out for lack of room and no admitted record stale or false.' },
  },
  {
    code: 'MEM',
    slug: 'mem',
    name: { en: 'MEM — Agent Memory Laboratory', tr: 'MEM — Ajan Belleği Laboratuvarı' },
    shortConcept: { tr: 'Arşiv unutmaz, depolar. Depoladığı şey eski, geçersiz kılınmış ya da düpedüz yanlış olabilir; ve tam bir güvenle geri verir.', en: 'The archive does not forget, it stores. What it stores can be old, superseded or simply wrong — and it will hand it back with complete confidence.' },
    description: { en: 'Explore agent memory across six synthetic scenarios and three memory policies: recall, source and version links, correction, expiry, deletion and JSON export.', tr: 'Ajan belleğini altı sentetik senaryo ve üç bellek politikasında keşfet: geri çağırma, kaynak ve sürüm bağları, düzeltme, süre sonu, silme ve JSON dışa aktarımı.' },
    sourceUrl: 'https://mem.aserdargun.com/',
    region: 'memory-council-city',
    system: 'evidence',
    stageId: 'r3-context-lantern',
    mechanic: { tr: 'Bir kaydı fenere alıyorsun, dünya onun altında değişiyor, sonra onu taşımadan önce düzeltiyor, geçersiz kılıyor ya da süresini dolduruyorsun. Tazelik ve doğruluk ayrı ayrı izlendiği için bir kayıt kendinden emin olup yine de reddedilebilir; fenerdeki yer de sınırlı.', en: 'You take a record into the lantern, let the world change underneath it, then correct, supersede or expire it before it is carried. Freshness and correctness are tracked separately, so a record can be confident and still be refused, and lantern room is finite.' },
    discovery: { tr: 'Arşiv, yazıldığı dünya hakkında doğruydu. Sadece o dünyanın hâlâ dışarıdaki dünya olup olmadığı hiç sorulmamıştı.', en: 'The archive had been right about the world it was written in. It had simply never been asked whether that world was still the one outside.' },
    questIds: ['r3-context-lantern', 'cross-x2'],
    completionCondition: { tr: 'Taşınan her kayıt hem dünyanın şu anki haline karşı taze hem de doğrudur ve fenerde yer sıkıntısıyla yerinden edilen bir şey yoktur.', en: 'Every record carried is both fresh against the world as it is now and correct, with nothing displaced for lack of lantern room.' },
  },
  {
    code: 'SEC',
    slug: 'sec',
    name: { en: 'AI Systems Security Observatory', tr: 'AI Sistemleri Güvenlik Gözlemevi' },
    shortConcept: { tr: 'Güven burada bir duygu değil, bir mühürdür. Her mühür yalnızca bir tür geçidi açar ve bir güven zinciri en dar mührü kadar güçlüdür.', en: 'Trust is not a feeling here, it is a seal. Each seal opens one kind of passage only, and a chain of trust is exactly as strong as its narrowest seal.' },
    description: { en: 'A bilingual, evidence-aware observatory for tracing AI-agent trust from model intent through identity, authorization, constrained action, audit, and incident recovery.', tr: 'Model niyetinden kimliğe, yetkilendirmeye, kısıtlı eyleme, denetime ve olay sonrası toparlanmaya kadar AI ajanlarına duyulan güveni izleyen iki dilli, kanıt duyarlı gözlemevi.' },
    sourceUrl: 'https://sec.aserdargun.com/',
    region: 'memory-council-city',
    system: 'connection',
    stageId: 'r3-permission-seals',
    mechanic: { tr: 'Zincirin parçaları arasına kanallar çekip her birinin ne taşıdığını izliyorsun. Bir kanalın iki ucu aynı türden olmalı ya da hattı reddederler; bir düğüm mührünün izin verdiğinden fazlasını iletmez, yukarıda cömert bir izin dar bir mührün ötesinde hiçbir işe yaramaz.', en: 'You draw conduits between the parts of the chain and watch what each carries. Two ends of a conduit must be the same kind or they refuse the line, and a node forwards no more than its own seal allows — so a generous grant upstream buys nothing past a narrow seal.' },
    discovery: { tr: 'İhlal hiçbir zaman gürültülü kapıda değildi. Herkes imzalı olduğu için güvendiği dar bir mührün içindeydi.', en: 'The breach was never in the loud gate. It was in a narrow seal everyone had trusted because it was signed.' },
    questIds: ['r3-permission-seals'],
    completionCondition: { tr: 'Her kanal eşleşen türleri birbirine bağlar ve mühürlü düğüm, dar hiçbir mühürde kaybolmadan zincirin taşıyabildiği miktarın tamamını alır.', en: 'Every conduit joins matching kinds, and the sealed node receives the full amount the chain can carry with no loss at any narrow seal.' },
  },
  {
    code: 'EVL',
    slug: 'evl',
    name: { en: 'AI Evaluation & Reliability Lab', tr: 'AI Değerlendirme ve Güvenilirlik Laboratuvarı' },
    shortConcept: { tr: 'Bir kez işe yarayan onarım onarım değildir. Onu birkaç koşulun içinden geçirmek gerekir; sessizce işe yaramayı bıraktığı koşullar not edilecek olanlardır.', en: 'A repair that works once is not a repair. You must take it through several conditions, and the ones where it quietly stops working are the ones worth writing down.' },
    description: { en: 'A bilingual, evidence-aware workbench for evaluation contracts and deterministic AI release decisions across output, trajectory, outcome, robustness, safety, and operations.', tr: 'Çıktı, izlenen yol, sonuç, sağlamlık, güvenlik ve operasyon katmanlarında değerlendirme sözleşmeleriyle belirlenebilir AI sürüm kararları üretmeye yarayan iki dilli, kanıt duyarlı çalışma alanı.' },
    sourceUrl: 'https://evl.aserdargun.com/',
    region: 'memory-council-city',
    system: 'connection',
    stageId: 'r3-permission-seals',
    mechanic: { tr: 'Mühürleri doğru mekanizmalara taktıktan sonra aynı düzeltmeyi birkaç koşulda sınıyorsun. Tek koşulda tutan ama sonrakinde tutmayan bir takım düzelmiş sayılmaz, kırılgan sayılır.', en: 'Once the seals sit on the right mechanisms you test the same repair under several conditions. A fix that holds for one condition and fails the next has not been repaired; it is reported as fragile.'},
    discovery: { tr: 'Adlandırdığım her koşulda geçti. Hata, adını koymayı düşünmediğim koşulun içindeydi.', en: 'It passed every condition I had chosen. The failure lived in the condition I had not thought to name.' },
    questIds: ['r3-permission-seals'],
    completionCondition: { tr: 'Bir onarım seçilir ve etkisinin tabandan farklı olması beklenen koşullar dâhil, her koşulda beklendiği gibi davranır.', en: 'A repair is chosen and it behaves as expected in every listed condition, including those where its effect should differ from the baseline.' },
  },
  {
    code: 'USL',
    slug: 'usl',
    name: { en: 'Unsloth Studio Learning Atlas', tr: 'Unsloth Studio Learning Atlas' },
    shortConcept: { tr: 'Limanın çocuğu örnekleri dikkatle okur. Bir kalıbı birebir kopyalayabilir, başkasından birkaç parça ödünç alabilir ya da neredeyse her şeyi gevşek bir yük halinde taşıyabilir. Her yol ondan ayrı bir bedel ister.', en: 'A harbour boy reads his examples carefully. He can copy one pattern exactly, borrow a few pieces from another, or carry almost everything loose in a bundle. Each way costs him differently.' },
    description: { en: 'A bilingual learning atlas with eight lessons, a 12-week roadmap, teaching labs and historical experiment evidence for LoRA/QLoRA, datasets, evaluation and local deployment. No live GPU or training; ADP extends adaptation practice with synthetic experiments.', tr: 'LoRA/QLoRA, veri setleri, değerlendirme ve yerel dağıtım için sekiz ders, 12 haftalık yol, öğretici laboratuvarlar ve geçmiş deney kanıtları sunan iki dilli atlas. Canlı GPU veya eğitim yoktur; ADP, uyarlama pratiğini sentetik deneylerle genişletir.' },
    sourceUrl: 'https://usl.aserdargun.com/',
    region: 'adaptation-cloud-harbor',
    system: 'allocation',
    stageId: 'r4-example-patterns',
    mechanic: { tr: 'İş yükünü atölyenin şeritlerine dağıtıyorsun: birebir kopya, kısmi ödünç, gevşek yük. Her birinin kendi yuvası, giriş ücreti ve sabrı var; en yavaş şerit limanın ne zaman kalkacağını belirliyor ve her parça kendisine uyan bir yere konmalı.', en: 'You distribute the workload onto the workshop’s lanes — exact copy, partial borrow, loose bundle — each with its own room, entry cost and patience. The slowest lane decides when the harbour can lift, and every part must be placed somewhere that suits it.' },
    discovery: { tr: 'Gevşek yük hiçbir zaman özensiz seçenek değildi. Birebir kopya bir daha sığmadığında tek sığan oydu.', en: 'The loose bundle was never the careless choice. It was the only one that still fitted once the exact copy stopped fitting.' },
    questIds: ['r4-example-patterns'],
    completionCondition: { tr: 'İş yükünün her parçası kendisine uyan bir şeride yerleşir, hiçbir şerit yuvasını ya da sabrını aşmaz ve en yavaş şerit liman süresi içinde kalkar.', en: 'Every part of the workload is placed on a lane that suits it, no lane exceeds its slots or patience, and the slowest lane lifts within the harbour’s time.' },
  },
  {
    code: 'ADP',
    slug: 'adp',
    name: { en: 'ADP — Model Adaptation Laboratory', tr: 'ADP — Model Uyarlama Laboratuvarı' },
    shortConcept: { tr: 'Bir makine yeniden kurulmadan da değiştirilebilir. Bazı değişiklikler her dişliye dokunur, bazıları yalnızca birkaçına. Mesele, küçük olan parçayı onu taşıyabilecek bir atölyeye yerleştirmek.', en: 'A machine can be changed instead of rebuilt. Some changes touch every gear, some touch only a few. The trick is putting the small enough part in a workshop that can actually hold it.' },
    description: { en: 'Explore Full FT, LoRA and QLoRA through parameter counts, memory estimates, data preparation and synthetic training/evaluation experiments. USL provides the adaptation foundation; an optional DCL handoff carries educational workload metadata into deployment planning. No real model is trained or deployed.', tr: 'Full FT, LoRA ve QLoRA yöntemlerini parametre sayıları, bellek tahminleri, veri hazırlığı ve sentetik eğitim/değerlendirme deneyleriyle keşfet. USL uyarlamanın temelini sunar; isteğe bağlı DCL aktarımı eğitim amaçlı iş yükü bilgilerini dağıtım planlamasına taşır. Gerçek model eğitilmez veya yayına alınmaz.' },
    sourceUrl: 'https://adp.aserdargun.com/',
    region: 'adaptation-cloud-harbor',
    system: 'allocation',
    stageId: 'r4-module-fit',
    mechanic: { tr: 'Modülleri seçip atölyenin gözlerine yerleştiriyorsun. Her gözün sınırlı yuvası, giriş ücreti ve dayanım sınırı var; yanlış türden bir göze konan modül de yer kaplıyor ve montaj en yavaş göz bitmeden tamamlanmıyor.', en: 'You pick modules and fit them into the workshop’s bays. Every bay has a limited slot count, an entry cost and a tolerance, and a module placed in the wrong kind of bay still takes up room — the assembly leaves only when the slowest bay is finished.' },
    discovery: { tr: 'Küçük değişiklik hiçbir zaman daha az bir makine değildi. Liman kapanmadan atölyenin bitirebileceği tek şeydi.', en: 'The small change was never a lesser machine. It was the only one the workshop could finish before the harbour closed.' },
    questIds: ['r4-module-fit'],
    completionCondition: { tr: 'Seçilen her modül doğru türden bir göze yuva ve dayanım sınırları içinde oturur ve montajın hiçbir parçası takılmaz hâlde kalmaz.', en: 'Every chosen module fits a bay of the right kind within its slot count and tolerance, and no part of the assembly is left unfitted.' },
  },
  {
    code: 'LCL',
    slug: 'lcl',
    name: { en: 'Local Compute Lab', tr: 'Local Compute Lab' },
    shortConcept: { tr: 'Bazı yükler kendi avlunuzda duran makinelerle taşınabilir, bazıları liman vinçlerine kaldırılmalı. Avlu başlamak için daha ucuz, büyümek için daha zordur.', en: 'Some freight is carried by the machines already standing in your own yard; some must be lifted by the harbour cranes. The yard is cheaper to start and harder to grow.' },
    description: { en: 'A bilingual, source-backed workbench matching open-weight model requirements to NVIDIA, AMD, and Apple devices. Explore dated market observations, memory assumptions, compatibility evidence, and concept cards; compare local and cloud deployment assumptions in the shared DCL lab.', tr: 'Açık ağırlıklı model gereksinimlerini NVIDIA, AMD ve Apple cihazlarıyla eşleştiren iki dilli, kaynaklı çalışma alanı. Tarihli fiyat gözlemlerini, bellek varsayımlarını, uyumluluk kanıtlarını ve kavram kartlarını incele; ortak DCL laboratuvarında yerel ve bulut dağıtım varsayımlarını karşılaştır.' },
    sourceUrl: 'https://lcl.aserdargun.com/',
    region: 'adaptation-cloud-harbor',
    system: 'allocation',
    stageId: 'r4-route-choice',
    mechanic: { tr: 'Her yükü liman haritasındaki bir şeride yönlendiriyorsun: avlu makineleri, liman vinçleri, yönetilen kaldırma, mekiğe taşımalar. Her birinin kendi kapasitesi, giriç ücreti ve gecikmesi var; her yük kendisini taşıyan şeridin dayanabileceği sınırlar içinde olmalı ve en yavaş şerit varışı belirliyor.', en: 'You route each payload onto a lane in the harbour chart — yard machines, harbour cranes, managed lifting, token hauls — each with its own capacity, entry cost and delay. Every payload must be tolerated by the lane that carries it, and the slowest lane sets the arrival.' },
    discovery: { tr: 'Avlu makinesi vinçten iyi değildi. Yük geldiğinde zaten oradaydı, sadece.', en: 'The yard machine was not better than the crane. It was simply already standing there when the freight arrived.' },
    questIds: ['r4-route-choice'],
    completionCondition: { tr: 'Her yük kendisini taşıyabilecek bir şeride yuva sınırları içinde yönlendirilir ve limanın en yavaş şeridi vardığında yönlendirilmemiş hiçbir yük kalmaz.', en: 'Every payload is routed onto a lane that tolerates it within its slot count, and nothing is left unrouted when the slowest lane arrives.' },
  },
  {
    code: 'CLD',
    slug: 'cld',
    name: { en: 'Cloud Provider Cost Comparison', tr: 'Bulut Sağlayıcı Maliyet Karşılaştırması' },
    shortConcept: { tr: 'Aynı kasa üç ayrı limandan kaldırılabilir. Her biri kendi sayma yöntemini kullanır ve en ucuz bilet, neyi taşıdığınızda ısrar ettiğinize bağlıdır.', en: 'The same crate can be lifted from three different harbours. Each charges its own way of counting, and the cheapest ticket depends on what you insist on carrying.' },
    description: { en: 'A source-backed decision tool comparing pre-tax USD costs for cloud services available from Türkiye.', tr: 'Türkiye’den erişilebilen bulut servislerini kaynaklı, vergiler hariç USD maliyetleriyle karşılaştıran karar destek aracı.' },
    sourceUrl: 'https://cld.aserdargun.com/',
    region: 'adaptation-cloud-harbor',
    system: 'allocation',
    stageId: 'r4-route-choice',
    mechanic: { tr: 'Yükün her kalemini bir liman şeridine yerleştiriyorsun. Her şerit birim başına farklı bir ek yük ve farklı bir hazırlık taşıyor, yani toplam biletlerin toplamı değil, seçtiğin her hazırlığın eklenmiş hâlidir; şeritler ayrıca yalnızca kendi türünden kasayı kabul ediyor.', en: 'You place each line of the shipment on a harbour lane. Each lane carries a different overhead per unit and a different setup, so the total is the sum of the tickets plus every setup you chose to open — and lanes accept only their own kind of crate.' },
    discovery: { tr: 'En ucuz liman hiç açmadığımız limandı. Pahalı olan ise zaten ödenmiş olan.', en: 'The cheapest harbour was the one we never opened. The expensive one was the one already paid for.' },
    questIds: ['r4-route-choice'],
    completionCondition: { tr: 'Her kalem kendisini kabul eden bir şeride yerleşir, hiçbir şerit yuvasının ötesinde yüklenmez ve maliyet kapanırken atanmamış hiçbir kalem kalmaz.', en: 'Every line is placed on a lane that accepts it, no lane is loaded past its slot count, and no line is left unassigned when the cost settles.' },
  },
  {
    code: 'DCL',
    slug: 'dcl',
    name: { en: 'Deployment Choice Laboratory', tr: 'Dağıtım Karar Laboratuvarı' },
    shortConcept: { tr: 'Liman sizin yerinize seçmez. Hatları serer: her taşıma yoluna bir hat, ve sizin onlara bindiğiniz sıra hangisine gerçekten bindiğinizi belirler.', en: 'The harbour does not choose for you. It lays out the tracks — one line per way of carrying — and the order you board them decides which one you actually ride.' },
    description: { en: 'The shared laboratory of CLD and LCL. Compare local hardware, cloud GPUs, managed inference and token APIs against workload, memory, privacy and cost assumptions. Hard constraints and educational estimates explain conditional choices; no live pricing or universal winner is claimed.', tr: 'CLD ve LCL’nin ortak laboratuvarı. Yerel donanım, bulut GPU, yönetilen çıkarım ve token API seçeneklerini iş yükü, bellek, gizlilik ve maliyet varsayımlarıyla karşılaştır. Kesin kısıtlar ve eğitim amaçlı tahminler koşullu kararları açıklar; canlı fiyat veya evrensel kazanan iddiası yoktur.' },
    sourceUrl: 'https://dcl.aserdargun.com/',
    region: 'adaptation-cloud-harbor',
    system: 'allocation',
    stageId: 'r4-route-choice',
    mechanic: { tr: 'Her iş yükünü kendi kısıtına göre bir rotaya yerleştiriyorsun: yerinde mi, uzakta mı, yoksa karışık mı. Her rotanın kendi kapasitesi, giriş ücreti ve gecikmesi var; hepsini göğe göndermek de hepsini yerinde tutmak da bir çözüm değil.', en: 'You place each workload onto a route that fits its own constraints: local, remote, or mixed. Every route carries its own capacity, entry cost and delay, and sending everything skyward is no more a solution than keeping everything local.'},
    discovery: { tr: 'Rotayı önce seçmiş, iş yükünü onu doğrulayacak biçimde şekillendirmiştim. Liman beni o sırayla bindiriyordu baştan beri.', en: 'I had chosen the route first and shaped the workload to justify it. The harbour had been boarding me in that order the whole time.' },
    questIds: ['r4-route-choice', 'cross-x3'],
    completionCondition: { tr: 'Dört dağıtım adımının tamamı tam bir kez yer alır ve her biri yalnızca bağımlı olduğu karar var olduğunda başlar.', en: 'All four deployment steps are placed exactly once, each one starting only after the decision it depends on already exists.' },
  },
  {
    code: 'SWI',
    slug: 'swi',
    name: { en: 'SWI — Swarm Intelligence', tr: 'SWI — Sürü Zekâsı' },
    shortConcept: { tr: 'Bahçede kimse emir vermez. Herkes birkaç yerel kurala uyar ve bütün bahçenin biçimi yalnızca o küçük kararların toplamıdır.', en: 'Nobody in the garden gives orders. Each one obeys a handful of local rules, and the shape of the whole garden is only ever the sum of those small decisions.' },
    description: { en: 'A bilingual swarm-intelligence atlas with eight biology dossiers, 21 selected studies and eight static agent experiment templates. SWI observes and explains; ANT and BEE own the colony simulations. Recipes export Markdown/JSON without running agents; the agenda stays in the browser.', tr: 'Sekiz biyoloji dosyası, seçilmiş 21 çalışma ve sekiz statik ajan deney şablonu sunan iki dilli sürü zekâsı atlası. SWI gözlemler ve açıklar; koloni simülasyonları ANT ve BEE’ye aittir. Reçeteler ajan çalıştırmadan Markdown/JSON üretir; gündem tarayıcıda kalır.' },
    sourceUrl: 'https://swi.aserdargun.com/',
    region: 'collective-gardens',
    system: 'allocation',
    stageId: 'r5-trail-routing',
    mechanic: { tr: 'Her arayanı bahçelerin bir terasına yerleştiriyorsun. Bir terasın kurduğu iz ancak üstüne koyduğun iş kadar güçlüdür; izler turlar arasında solar ve geçen turda en güçlü olan rota şimdi en zayıfı olabilir.', en: 'You place each forager on a terrace of the gardens. A trail is only as strong as the work you put on it, trails fade between rounds, and a route that was strongest last round may be the weakest one now.' },
    discovery: { tr: 'Bahçede hiçbir zaman bir lider olmadı. Yalnızca herkesin aynı anda uyduğu bir kural vardı.', en: 'There was never a leader in the garden. There was only a rule that everyone obeyed at the same moment.' },
    questIds: ['r5-trail-routing'],
    completionCondition: { tr: 'Her arayan kendi türünden bir terasada durur ve geriye kalan en güçlü iz, eski bir yol değil, terasanın kaynağına ulaşan izdir.', en: 'Every forager sits on a terrace of its own kind, and the strongest remaining trail is the one that reaches the source rather than an old path.' },
  },
  {
    code: 'ANT',
    slug: 'ant',
    name: { en: 'ANT — Ant Colony Intelligence Laboratory', tr: 'ANT — Karınca Kolonisi Zekâ Laboratuvarı' },
    shortConcept: { tr: 'Her karınca bir iz bırakır ve her saat onu biraz unutur. Koloni iyi yolu hatırlamaz; en son en güçlü kokan yolu hatırlar.', en: 'Each ant leaves a mark and forgets a little of it every hour. The colony does not remember the good road; it remembers the road that smelled strongest most recently.' },
    description: { en: 'SWI’s companion ant-colony lab: one reproducible experiment, three guided exercises and run replay. Explore local rules, food-pheromone trails and evaporation. Home chemical is observational; returning ants use idealized path integration. No species calibration or guaranteed shortest path; synchronized A/B is future work.', tr: 'SWI’ye eşlik eden karınca kolonisi laboratuvarı: bir tekrarlanabilir deney, üç rehberli çalışma ve deney kaydı tekrarı. Yerel kuralları, besin feromonu izlerini ve sönümü incele. Yuva kimyasalı gözlem içindir; dönen karıncalar idealize yol bütünlemesi kullanır. Türe kalibrasyon veya en kısa yol garantisi yoktur; eşzamanlı A/B ileriki aşamadır.' },
    sourceUrl: 'https://ant.aserdargun.com/',
    region: 'collective-gardens',
    system: 'allocation',
    stageId: 'r5-trail-routing',
    mechanic: { tr: 'Aryanları teras karoları boyunca gönderip izlerin her turda sönmesine izin veriyorsun. Her turda en güçlü iz kazanır, kapalı karolar hiç iz tutmaz ve kazanan iz kesildiğinde koloni yenisine yerleşmeden hareket edemez.', en: 'You send foragers across the terrace tiles and let the trails evaporate turn by turn. The strongest trail wins each turn, blocked tiles keep no trace at all, and when the winning trail is closed the colony must re-settle onto a new one before it moves.' },
    discovery: { tr: 'Koloni hiçbir zaman en kısa yolu öğrenmedi. Unutmayı öğrendi ve hareket edebilmesini sağlayan da unutmaktı.', en: 'The colony never learned the shortest path. It learned to forget, and forgetting was the part that let it move.' },
    questIds: ['r5-trail-routing', 'cross-x1'],
    completionCondition: { tr: 'Koloni arayanları bu tur hâlâ var olan bir izle kaynağa ulaşır ve hiçbir arayan çoktan solmuş bir izin peşinde kalmaz.', en: 'The colony’s foragers reach the source along a trail that still exists this turn, and none is left following a trace that has already faded.' },
  },
  {
    code: 'BEE',
    slug: 'bee',
    name: { en: 'BEE — Honey Bee Collective Intelligence Laboratory', tr: 'BEE — Bal Arısı Kolektif Zekâ Laboratuvarı' },
    shortConcept: { tr: 'Bir arı tek başına gidebilir ya da eve dönüp diğerleri onunla gelsin diye yeterince dans edebilir. Dans zaman kaybettirir ama kimse aynı çiçeği iki kez keşfetmez.', en: 'A bee can go it alone, or come home and dance long enough for the others to come with her. Dancing costs time but nobody has to discover the same flower twice.' },
    description: { en: 'Four deterministic, bilingual experiments within SWI’s research family: explore local discovery, private memory, dance recruitment and resource allocation with a same-seed dance-off control, guided lessons and JSON replay. An Apis mellifera-inspired educational model; results use model units, not field measurements or biological predictions.', tr: 'SWI araştırma ailesinde dört deterministik, iki dilli deney: yerel keşfi, bireysel hafızayı, dansla katılımı ve kaynak dağılımını aynı seed ile dansı kapalı kontrol, rehberli dersler ve JSON yeniden oynatma ile incele. Apis mellifera esinli eğitim modelidir; sonuçlar model birimleridir, saha ölçümü veya biyolojik tahmin değildir.' },
    sourceUrl: 'https://bee.aserdargun.com/',
    region: 'collective-gardens',
    system: 'allocation',
    stageId: 'r5-dance-floor',
    mechanic: { tr: 'Kolonyayı çiçek teraslarına bölüyor ve her tur dans edip etmeyeceğine karar veriyorsun. Dans eden koloni kısa bir gecikmenin ardından herkesi en iyi bilinen tarlaya gönderiyor; sessiz olan yayılıyor ve her arayanın bulduğunun ortalamasını alıyor.', en: 'You split the colony across the flower terraces and decide each round whether the colony dances. A dancing colony sends everyone to the best-known field after a short delay, while a silent one spreads out and takes the average of what each forager found.' },
    discovery: { tr: 'Dans ettiğinde koloni tembel değildi. Turlarını bilinçli harcıyor, bulduğu çiçekle zaman satın alıyordu.', en: 'The colony was not lazy when it danced. It was spending its rounds deliberately, buying time with the flower it had already found.' },
    questIds: ['r5-dance-floor'],
    completionCondition: { tr: 'Her arayan bir terasaya yerleştirilir, her tur koloninin dans tercihi seçilir ve toplanan miktar şansa değil bu seçime uyar.', en: 'Every forager is placed on a terrace, the colony’s dance setting is chosen each round, and the total gathered matches the choice rather than luck.' },
  },
  {
    code: 'VIS',
    slug: 'vis',
    name: { en: 'Computer Vision Knowledge Bank', tr: 'Bilgisayarlı Görü Bilgi Bankası' },
    shortConcept: { tr: 'Ayna sana kenarları gösterebilir, nesnelerin uzaklığını gösterebilir ya da neyin kıpırdadığını — ama asla ikisini birden, ve her biri kendi biçiminde yalan söyler.', en: 'The mirror can show you edges, or how far things are, or what moved — never two at once, and each lies in its own way.' },
    description: { en: 'A source-backed computer-vision field guide across seven perception layers, each layer naming what it is not for, plus a deterministic laboratory that measures the same ideas against a per-pixel answer key. The knowledge bank explains and cites; the laboratory measures. Classical operators, a CNN trained at runtime, monocular depth cues and optical flow all run on a CPU path by default and an honestly probed WebGPU path when available.', tr: 'Yedi algı katmanında birincil kaynaklara bağlı bilgisayarlı görü alan rehberi; her katman ne için olmadığını da söyler ve yanında aynı fikirleri piksel başına cevap anahtarına karşı ölçen deterministik bir laboratuvar bulunur. Bilgi bankası açıklar ve kaynak gösterir; laboratuvar ölçer. Klasik operatörler, çalışma anında eğitilen bir CNN, monoküler derinlik ipuçları ve optik akış varsayılan CPU yolunda, mevcutsa dürüstçe yoklanan WebGPU yolunda çalışır.' },
    sourceUrl: 'https://vis.aserdargun.com/',
    region: 'observers-mirrors',
    system: 'perception',
    stageId: 'r6-lens-layers',
    mechanic: { tr: 'Dev aynaya bir mercek takıyor ve oyulmuş sahne üzerinde sınırlı okuma bütçeni harcıyorsun. Her merceğin kendi kör noktası var: kenar merceği katı bir formun arkasında kalanı çözemiyor, derinlik merceği az ışıkta çöküyor, hareket merceği ise sahne bir kez görülmeden hiçbir şey bildirmiyor.', en: 'You mount one lens in the great mirror and spend its limited reading budget over the engraved scene. Each lens has its own blind spot — the edge lens cannot resolve what stands behind a solid form, the depth lens collapses in poor light, and the motion lens reports nothing until the scene has been observed once before.' },
    discovery: { tr: 'Öğleden sonrayı merceği suçlamakla geçirdim. Mercek görebildiği her şeyde doğruydu; yalnızca erişimi düşündüğümden daha küçük bir dünya vardı.', en: 'I had spent the afternoon blaming the lens. It was right about everything it could see; there was simply less of the world inside its reach than I assumed.' },
    questIds: ['r6-lens-layers', 'cross-x1'],
    completionCondition: { tr: 'Tek bir mercek sahnedeki her hücreyi, yanlış bildirilen ve çözülemeyen hiçbir hücre olmadan okuma bütçesi içinde okur.', en: 'One lens reads every cell of the scene with no cell misreported and none left unresolved, within its reading budget.' },
  },
  {
    code: 'CVL',
    slug: 'cvl',
    name: { en: 'Computer Vision Laboratory', tr: 'Computer Vision Laboratory' },
    shortConcept: { tr: 'İkinci aynanın arkasında bir cevap anahtarı var. Sana merceğin çalışıp çalışmadığı sorulmuyor; nerede doğruyu söylemeyi bıraktığı soruluyor.', en: 'Behind the second mirror there is an answer key. You are not being asked whether the lens works — you are being asked where it stopped telling the truth.' },
    description: { en: 'Compare lens outputs against a known synthetic test scene and discover failures caused by occlusion or changing light.', tr: 'Mercek çıktılarını bilinen sentetik bir test sahnesiyle karşılaştır ve örtüşmeden ya da değişen ışıktan kaynaklanan hataları keşfet.' },
    sourceUrl: 'https://cvl.aserdargun.com/',
    region: 'observers-mirrors',
    system: 'perception',
    stageId: 'r6-lens-layers',
    mechanic: { tr: 'Aynı merceği aynı sahnede ikinci kez koşturup her hücreyi bilinen cevapla karşılaştırıyorsun. Hangi katmanın başarısız olduğu sana adıyla bildiriliyor: örtüşen hücreler boş okunuyor, karanlık hücreler derinlik okumasını çökertiyor ve sessiz kalan hücre tahmin sayılmak yerine eksik olarak bildiriliyor.', en: 'You run the same lens over the same scene a second time and compare every cell with the known answer. The layer that fails is named for you — occluded cells read as empty, dim cells collapse the depth readout, and a silent cell is reported as missing rather than counted as a guess.' },
    discovery: { tr: 'Hatalar hiçbir zaman rastgele değildi. Her biri cevap anahtarının ışığın kısa olacağını söylediği yerdeydi.', en: 'The failures were never random. Every one of them sat exactly where the answer key said the light would be short.' },
    questIds: ['r6-lens-layers'],
    completionCondition: { tr: 'Mercek, daha önce örtüşme ve az ışık yüzünden başarısız olan yerler dâhil, sahne boyunca yanlış bildirilen ve çözülemeyen sıfır hücre bildirir.', en: 'The lens reports zero wrong cells and zero unresolved cells across the scene, including where occlusion and dim light had failed before.' },
  },
  {
    code: 'WFM',
    slug: 'wfm',
    name: { en: 'World Models Atlas', tr: 'World Models Atlas' },
    shortConcept: { tr: 'Dünya modeli delikleri olan bir haritadır. Sizin için doldurduğu her şey bir varsayımdır ve hiç görmediği parçalar yanlış çıktığında maliyeti iki katına çıkar.', en: 'A world model is a map with holes in it. Everything it fills in for you is an assumption, and the parts it never saw cost double when they turn out wrong.' },
    description: { en: 'A living research atlas tracing how world models connect perception, prediction, planning, and action through primary sources.', tr: 'Dünya modellerinin algı, tahmin, planlama ve eylem arasındaki rolünü birincil kaynaklar üzerinden izleyen yaşayan bir araştırma atlası.' },
    sourceUrl: 'https://wfm.aserdargun.com/',
    region: 'observers-mirrors',
    system: 'prediction',
    stageId: 'r6-passage-model',
    mechanic: { tr: 'Geçidi iki listeden kuruyorsun: merceklerin gerçekten gördükleri ve modelin yalnızca varsaydıkları. Sonra onu sahnenin gerçekte ne çıktığına karşı tartıyorsun; varsayım üzerine duran hücreler bir plana iki kez ağır geliyor, yani deliklerle dolu bir harita küçük ama emin bir haritadan çok daha yüksek belirsizlik bildirir.', en: 'You build the passage from two lists — what the lenses genuinely observed and what the model merely assumed — then weigh it against what the scene actually turned out to be. Cells resting on assumption count twice against a plan, so a map full of holes reports far more uncertainty than a small sure one.' },
    discovery: { tr: 'Model birçok yerde yanlış değildi. Yanlış olduğu yerler, bakmayı kabul ettiği yerlerdi.', en: 'The model was not wrong in many places. It was wrong in the places it had agreed not to look.' },
    questIds: ['r6-passage-model'],
    completionCondition: { tr: 'Geçit, varsayılan her hücre varsayım olarak işaretlenerek kurulur ve model aynı tahminler gözlem sayılarak kurulmuş özdeş bir plandan daha düşük belirsizlik bildirir.', en: 'The passage is built with every assumed cell marked as assumed, and the model reports a lower uncertainty than an identical plan that treated the same guesses as observations.' },
  },
  {
    code: 'WML',
    slug: 'wml',
    name: { en: 'World Model Laboratory', tr: 'Dünya Modeli Laboratuvarı' },
    shortConcept: { tr: 'Hareket etmeden önce ayna, gitmediğin yolu da gösteriyor. Kendinden emin, ayrıntılı ve yine de yalnızca bir söz.', en: 'Before you move, the mirror offers to show you the road not taken. It is confident, it is detailed, and it is still only a promise.' },
    description: { en: 'Explore observation, belief, prediction, planning, and counterfactual branches in WFM’s experiment laboratory. Compare three hand-coded predictors against a simulated world; these are not trained foundation models.', tr: 'WFM’nin deney laboratuvarında gözlemi, inancı, tahmini, planlamayı ve alternatif eylem dallarını keşfet. Elle tanımlanmış üç tahmin modelini simüle edilen dünyayla karşılaştır; bunlar eğitilmiş temel modeller değildir.' },
    sourceUrl: 'https://wml.aserdargun.com/',
    region: 'observers-mirrors',
    system: 'prediction',
    stageId: 'r6-counterfactual',
    mechanic: { tr: 'İkinci bir dalı ilkinin yanında açıp her birine bir sonuç veriyorsun; sonra eyleme geçiyorsun ve dünya seçtiğin dalın vaat ettiğini gerçekte olanla karşılaştırıyor. Ayrıca reddettiğin yolun daha iyi olup olmadığını da soruyor.', en: 'You open a second branch beside the first and give each an outcome, then act; the world compares what the chosen branch promised against what actually happened — and separately asks whether the road you declined was better.' },
    discovery: { tr: 'Diğer yol tam korktuğum kadar kötüydü; bana kendi korkumun ne kadar iyi tanıdığım dışında hiçbir şey söylemedi.', en: 'The other road was worse by exactly as much as I had feared, which told me nothing except how well I knew my own fear.' },
    questIds: ['r6-counterfactual', 'cross-x2'],
    completionCondition: { tr: 'İki dal önizlenir ve biri seçilir; seçilen dal kusursuzluğa değil, elde olan en iyi seçeneğe karşı değerlendirilir.', en: 'Two branches are previewed and one is chosen, and the chosen branch is judged against the best available option rather than against perfection.' },
  },
  {
    code: 'ITL',
    slug: 'itl',
    name: { en: 'Industrial Twin Lab', tr: 'Industrial Twin Lab' },
    shortConcept: { tr: 'Suya dokunma izniniz yok. Onun ne yapacağını yazarsınız, sonra başka bir şey yaptığını izler ve onu da yazarsınız.', en: 'You do not get to touch the water. You get to write down what you think it will do, then watch it do something else and write that down too.' },
    description: { en: 'An English research publication with authored deterministic P-101 evidence fixtures. Explore pump anatomy in PDT and computed synthetic decision experiments in DTR; each application has separate models and state, with no field connection or control authority.', tr: 'Hazırlanmış deterministik P-101 kanıt örnekleri sunan İngilizce araştırma yayını. PDT pompa anatomisini, DTR hesaplanan sentetik karar deneylerini keşfettirir; uygulamaların modelleri ve durumları ayrıdır, saha bağlantısı veya kontrol yetkisi yoktur.' },
    sourceUrl: 'https://itl.aserdargun.com/',
    region: 'valley-living-machines',
    system: 'prediction',
    stageId: 'r7-water-model',
    mechanic: { tr: 'Vadinin suyu için beklenen bir okuma çizgisi yazıyor ve pompanın gerçekte ürettiğiyle karşılaştırıyorsun. Bir tahmin ancak okumaların çoğunda tuttuğunda bir sonucu destekler ve hiçbir zaman kanıtlanmış olarak kaydedilmez.', en: 'You write an expected line of readings for the valley’s water and compare it with what the pump actually produced. A prediction only supports a conclusion when it holds across most of the readings, and it is never recorded as proven.' },
    discovery: { tr: 'Model neredeyse her okumada tuttu ve yine de vadinin içindeki makineden başka bir makineyi tarif ediyordu.', en: 'The model matched on nearly every reading and still described a different machine than the one in the valley.' },
    questIds: ['r7-water-model'],
    completionCondition: { tr: 'Yazılan model on okumanın en az sekizinde tolerans içinde tutar ve vardığı sonuç kanıtlanmış olarak değil, kanıtla tutarlı olarak kaydedilir.', en: 'The written model holds within tolerance across at least eight readings of ten, and its conclusion is recorded as consistent with evidence rather than as proven.' },
  },
  {
    code: 'PDT',
    slug: 'pdt',
    name: { en: 'P-101 Interactive Digital Twin', tr: 'P-101 Etkileşimli Dijital İkiz' },
    shortConcept: { tr: 'Pompa hepimizin duyduğu ama kimsenin adını koyamadığı bir ses çıkarıyor. En yüksek ses bir yeri gösteriyor; sebep başka bir yerde duruyor.', en: 'The pump makes a noise you can all hear and none of you can name. The loudest signal points somewhere; the cause sits somewhere else.' },
    description: { en: 'Explore P-101 through four views, nine components, eight sensor locations and five authored pump conditions. Compare qualitative synthetic signals; this ITL teaching companion has no live telemetry or shared experiment state.', tr: 'P-101’i dört görünüm, dokuz bileşen, sekiz sensör konumu ve beş kurgulanmış pompa durumuyla keşfet. Nitel sentetik sinyalleri karşılaştır; bu ITL eğitim uygulaması canlı telemetri veya ortak deney durumu içermez.' },
    sourceUrl: 'https://pdt.aserdargun.com/',
    region: 'valley-living-machines',
    system: 'prediction',
    stageId: 'r7-pump-diagnosis',
    mechanic: { tr: 'Pompanın çevresine, olası arızalar kümesi tek bir adaya inene dek sensörler yerleştiriyorsun, sonra onu adlandırıyorsun. Adlandırmak yetmez: sebebin gerçekten göründüğü bir sinyali de görmüş olman gerekir ve yalnızca birlikte göründüğü için gürültülü olan bir sinyale yaslanmamış olmalısın.', en: 'You place sensors around the pump until the set of possible faults narrows to one, then name it. Naming it is not enough — you must also have observed a signal where the cause actually shows, and must not have leaned on a signal that was merely loud.' },
    discovery: { tr: 'Hepimizin izlediği sinyal pompanın boğazını temizlemesiymiş. Arkasında bir conta aylardır sessizce aşınmaktaymış.', en: 'The signal everyone had been following was the pump clearing its throat. Behind it, a seal had been wearing down quietly for months.' },
    questIds: ['r7-pump-diagnosis', 'cross-x1'],
    completionCondition: { tr: 'Sensörler arızayı tek bir adaya indirir, gerçek arıza adlandırılır ve yalnızca birlikte görünen bir sinyal temel alınmaz.', en: 'Sensors narrow the fault to a single candidate, the true fault is named, and no merely correlated signal is used as the basis.' },
  },
  {
    code: 'DTR',
    slug: 'dtr',
    name: { en: 'DTR — Digital Triplet Laboratory', tr: 'DTR — Dijital Üçüz Laboratuvarı' },
    shortConcept: { tr: 'Vana odası iki ayar sunuyor. Biri insandan evet demesini istiyor. Su hareket ettikten sonra tahmin ettiğin sayı ile gerçekten aldığın sayı gösteriliyor.', en: 'The valve room offers two settings. One of them needs a person to say yes. After the water moves, you are shown the number you predicted and the number you got.' },
    description: { en: 'Explore six synthetic pumping scenarios with an independent twin, three 60-second alternatives, explicit human approval, prediction–outcome comparison and JSON experiment records. Runs entirely in the browser with explainable rules; no LLM, field telemetry or machine commands.', tr: 'Altı sentetik pompalama senaryosunda bağımsız ikizi, 60 saniyelik üç alternatifi, açık insan onayını, tahmin–sonuç karşılaştırmasını ve JSON deney kaydını incele. Açıklanabilir kurallarla tamamen tarayıcıda çalışır; LLM, saha telemetrisi veya makine komutu yoktur.' },
    sourceUrl: 'https://dtr.aserdargun.com/',
    region: 'valley-living-machines',
    system: 'prediction',
    stageId: 'r7-two-options',
    mechanic: { tr: 'Her iki ayarı vaat ettikleri sonuçlarla önizliyor, tam olarak birini onaylıyor, koşmasını sağlıyor ve söz ile gerçeklik arasındaki işaretli farkı okuyorsun. Oda diğer ayarın daha iyi olup olmayacağını asla gizlemez.', en: 'You preview both settings with their promised outcomes, approve exactly one, let it run and read the signed gap between the promise and reality. The room never hides whether the other setting would have done better.' },
    discovery: { tr: 'Kazanan ayarı onaylamıştım; oda ise onu yanlış gerekçeyle onayladığımı sessizce kayda geçirmişti.', en: 'I had approved the setting that won, and the room had quietly recorded that I had approved it for the wrong reason.' },
    questIds: ['r7-two-options'],
    completionCondition: { tr: 'Her iki seçenek önizlenir, tam olarak biri onaylanır ve koşumdan sonra vaat edilen sonuç gerçek olanla karşılaştırılır.', en: 'Both options are previewed, exactly one is approved, and the promised outcome is compared with the actual one after the run.' },
  },
  {
    code: 'ENG',
    slug: 'eng',
    name: { en: 'Open Humanoid Engineering', tr: 'Open Humanoid Engineering' },
    shortConcept: { tr: 'Yardımcı bir biçim değil, bir zincirdir. Bir uçta güç, diğer uçta algı ve aradaki her eklem, zincirin bir yere ulaşıp ulaşamayacağına karar verir.', en: 'A helper is not a shape, it is a chain. Power at one end, sense at the other, and every joint in between decides whether the chain ever reaches anything.' },
    description: { en: 'The learning system’s humanoid engineering horizon: an English manifesto following ITL, with HEX as its exploration companion. The proposed four-year spine, AI lab pipeline, and dated 2026 frontier signals are primary sources of truth. Seven specializations lead to portfolios; no degree, running AI laboratory, or completed physical robot is claimed.', tr: 'Öğrenme sisteminin insansı robot mühendisliği ufku: ITL’den ilerleyen, HEX’in keşifle eşlik ettiği İngilizce manifesto. Önerilen dört yıllık omurga, AI laboratuvar akışı ve tarihli 2026 araştırma sinyalleri temel doğruluk kaynaklarıdır. Yedi uzmanlık portföye yönelir; diploma, çalışan AI laboratuvarı veya tamamlanmış fiziksel robot iddiası yoktur.' },
    sourceUrl: 'https://eng.aserdargun.com/',
    region: 'valley-living-machines',
    system: 'placement',
    stageId: 'r7-helper-design',
    mechanic: { tr: 'Yardımcının adımlarını sıraya koyuyorsun: önce algılamak, sonra beslenmek, sonra karar vermek gerekiyor. Sıra bozulursa hiçbir parça yerine gelmiyor; doğru kurulunca yardımcı ulaşamadığı bağlantıya uzanıyor.', en: 'You order the helper’s sequence: it must sense first, then draw power, then decide. Break the order and no part lands in place; build it correctly and the helper reaches the connection it could not touch before.'},
    discovery: { tr: 'Yardımcı güçten değil eklemden yoksundu; yol uzundu ve her eklem bir pay aldı.', en: 'The helper was not out of strength. It was out of joints — the path was long and every one of them charged a toll.' },
    questIds: ['r7-helper-design'],
    completionCondition: { tr: 'Yardımcının her kanalı eşleşen türleri birleştirir ve hiçbir eklem kısmını düşürmeden uç noktaya sinyalin tamamı ulaşır.', en: 'Every conduit in the helper joins matching kinds and the far end receives the full signal with no joint dropping part of it.' },
  },
  {
    code: 'HEX',
    slug: 'hex',
    name: { en: 'Humanoid Engineering Explorer', tr: 'İnsansı Robot Mühendisliği Gezgini' },
    shortConcept: { tr: 'Eklemleri ve onların hangi sırayla kurulacağını sen seçersin. Dizleri bacaklardan önce kurarsan çok hassas bir parça yığını elde edersin.', en: 'You choose the joints and the order they are built in. Build the knees before the legs and you end up with a very precise pile of parts.' },
    description: { en: 'Explore humanoid structure, joints, actuation, sensors, and power/data paths through ENG’s interactive 3D learning object. Movements are kinematic teaching aids, with no asserted dynamics or hardware performance.', tr: 'ENG’nin etkileşimli 3B öğrenme uygulamasında insansı robot yapısını, eklemleri, eyleyicileri, sensörleri ve güç/veri yollarını keşfet. Hareketler kinematik öğretim örnekleridir; dinamik veya donanım performansı iddiası taşımaz.' },
    sourceUrl: 'https://hex.aserdargun.com/',
    region: 'valley-living-machines',
    system: 'placement',
    stageId: 'r7-helper-design',
    mechanic: { tr: 'Montajı sıralıyorsun: önce taban, sonra eklemler, sonra eyleyiciler, en tepede algı. Her aşama yalnızca altındaki aşama kapandıktan sonra koşuyor, her aşama tam bir kez yer alıyor ve tezgâh çok erken istediğin ilk eklemi bildiriyor.', en: 'You order the assembly — base, then joints, then actuation, then the sense at the top. Each stage runs only once the one below it has closed, every stage appears exactly once, and the bench names the first joint you asked for too early.' },
    discovery: { tr: 'Her eklem doğru yere oturduğunda yardımcı bir ağırlığı kaldırabiliyordu; üstündekini taşıyabilmesi için altındakinin önce orada olması gerekiyordu.', en: 'The helper could hold a weight once every joint was in the right place, and every joint had to be there before the one above it could carry.' },
    questIds: ['r7-helper-design', 'cross-x3'],
    completionCondition: { tr: 'Montajın her aşaması, hiçbir eklem üzerine takıldığı eklem var olmadan kurulmayan bir sırada tam bir kez yer alır.', en: 'Every assembly stage appears exactly once in an order where no joint is built before the one it mounts onto exists.' },
  },
];
