import { Component, Suspense, useEffect, useMemo, type ReactNode } from 'react';
import { useGLTF } from '@react-three/drei';
import type { Group, Material, Mesh } from 'three';

/**
 * Blender-authored asset loading.
 *
 * The models in `public/models` are generated by `tools/blender/build_assets.py`.
 * If any file is missing or unreadable the boundary below silently falls back to
 * the procedural geometry in `World.tsx`, so an absent asset degrades the look
 * but never blocks play.
 */

const MODEL_BASE = '/models/';

/** Uniform scale applied to Blender-authored assets to match world units. */
const MODEL_SCALE: Record<string, number> = {
  weaver: 1,
  spark: 1,
};

export function modelPath(name: string): string {
  return `${MODEL_BASE}${name}.glb`;
}

/**
 * Catches a failed model load. R3F surfaces a failed fetch as a thrown error
 * from the suspending promise, which React routes to the nearest boundary.
 */
class AssetBoundary extends Component<
  { fallback: ReactNode; children: ReactNode },
  { failed: boolean }
> {
  state = { failed: false };

  static getDerivedStateFromError() {
    return { failed: true };
  }

  componentDidCatch(error: unknown) {
    if (import.meta.env.DEV) {
      console.warn('[ILMEK] falling back to procedural geometry:', error);
    }
  }

  render() {
    return this.state.failed ? this.props.fallback : this.props.children;
  }
}

export interface LoadedModel {
  scene: Group;
  animations: never[];
}

function useModel(name: string): LoadedModel {
  return useGLTF(modelPath(name)) as unknown as LoadedModel;
}

/** Warm the loader so the first frame does not stall. */
export function preloadModels(names: string[]): void {
  for (const name of names) {
    try {
      useGLTF.preload(modelPath(name));
    } catch {
      /* a missing model simply falls back at render time */
    }
  }
}

/**
 * Locomotion states the player character can be in.
 *
 * The adopted CC0 character (KayKit Adventurers, Kay Lousberg — CC0-1.0) ships
 * far more clips than the game uses; `CLIP_FOR_STATE` maps the four states the
 * player can actually be in onto the source clips. Turn uses the two strafe
 * clips, which is what they animate.
 */
export type LocomotionState = 'idle' | 'walk' | 'run' | 'turnLeft' | 'turnRight';

export const CLIP_FOR_STATE: Record<LocomotionState, string> = {
  idle: 'Idle',
  walk: 'Walking_A',
  run: 'Running_A',
  turnLeft: 'Running_Strafe_Left',
  turnRight: 'Running_Strafe_Right',
};

export const LOCOMOTION_STATES: readonly LocomotionState[] = [
  'idle', 'walk', 'run', 'turnLeft', 'turnRight',
];

/**
 * The source model is authored at 3.36 units tall with its feet at y = -1.16.
 * Scaling and lifting it here puts the boots on the ground at world y = 0.
 */
export const CHARACTER_SCALE = 0.6;
export const CHARACTER_Y_OFFSET = 0.7;

export const ALL_MODEL_NAMES = [
  'weaver',
  'spark',
  'synthesis_tree',
  'tapestry',
  'console',
  'terrace_map',
  'great_loom',
  'council_city',
  'cloud_harbour',
  'collective_gardens',
  'observer_mirrors',
  'living_valley',
];

export interface AssetProps {
  /** File name under `/models`, without the extension. */
  name: string;
  /** Rendered when the model cannot be loaded. */
  fallback: ReactNode;
  position?: [number, number, number];
  rotation?: [number, number, number];
  scale?: number;
  /** Uniform scale applied only to the model, leaving the fallback untouched. */
  visible?: boolean;
}

/**
 * Renders a Blender asset when it is available, otherwise the supplied
 * procedural fallback. `position` and `rotation` are applied either way so the
 * two representations occupy exactly the same place in the world.
 */
export function Asset({
  name,
  fallback,
  position,
  rotation,
  scale,
  visible,
}: AssetProps) {
  return (
    <AssetBoundary fallback={fallback}>
      <Suspense fallback={fallback}>
        <AssetMesh
          name={name}
          position={position}
          rotation={rotation}
          scale={scale}
          visible={visible}
        />
      </Suspense>
    </AssetBoundary>
  );
}

function AssetMesh({
  name,
  position,
  rotation,
  scale,
  visible,
}: Omit<AssetProps, 'fallback'>) {
  const { scene } = useModel(name);
  const resolved = useMemo(() => scale ?? MODEL_SCALE[name] ?? 1, [scale, name]);

  useEffect(() => {
    // Trailing colour-space correction so PBR materials match the procedural
    // meshes rendered elsewhere in the scene.
    scene?.traverse((child: unknown) => {
      const mesh = child as Mesh;
      // A loaded GLB carries no shadow flags: the glTF format has no concept
      // of them, so every landmark was floating until it was told to cast and
      // receive like the procedural geometry around it.
      if (mesh.isMesh) {
        mesh.castShadow = true;
        mesh.receiveShadow = true;
      }
      const material = mesh.material as Material | undefined;
      if (!material) return;
      // Raised from 0.7 now that a real environment probe exists. The original
      // value was chosen against a scene with no reflections at all, where a
      // higher one only washed the metal out.
      if ('envMapIntensity' in material) {
        material.envMapIntensity = 1;
      }
      // Vertex AO, baked in Blender, arrives in COLOR_0. The material has to be
      // told to read it — glTF does not switch this on by itself, so without
      // this the bake loads and is never seen.
      if ('vertexColors' in material && mesh.geometry?.getAttribute('color')) {
        (material as { vertexColors: boolean }).vertexColors = true;
      }
    });
  }, [scene]);

  if (!scene || visible === false) return null;
  return (
    <primitive
      object={scene}
      position={position}
      rotation={rotation}
      scale={resolved}
    />
  );
}